export const screenName = {
  SplashScreen: 'SplashScreen',
  OnboardingScreen: 'OnboardingScreen',
  RoleSelectionScreen: 'RoleSelectionScreen',
  HomeScreen: 'HomeScreen',
  LoginSignupScreen: 'LoginSignupScreen',
  SignInScreen: 'SignInScreen',
  SignUpScreen: 'SignUpScreen',
  ForgotScreen: 'ForgotScreen',
  VerificationCode: 'VerificationCode',
  LocationScreen: 'LocationScreen',
  BottomTabBar: 'BottomTabBar',
  tab_bar_name: {
    Home: 'Home',
    FoodList: 'FoodList',
    MenuList:'MenuList',
    AddFoodDetails: 'AddFoodDetails',
    Notification: 'Notification',
    Profile: 'Profile',
  },
  FoodDetails: 'FoodDetails',
  MyOrdersList: 'MyOrdersList',
  ProfileNotification: 'ProfileNotification',
  ProfileMessages: 'ProfileMessages',
  ReviewsScreen: 'ReviewsScreen',
  PersonalInfo: 'PersonalInfo',
  EditProfile: 'EditProfile',
  Settings: 'Settings',
  CuisinesNameList: 'CuisinesNameList',
  NewPassword: 'NewPassword',
  EditFoodDetails: 'EditFoodDetails',
  EditMenuList:'EditMenuList',
  OrderHistory: 'OrderHistory',
  CuisinesEdit: 'CuisinesEdit',
  CuisinesAdd: 'CuisinesAdd',
  Support: 'Support',
  RecipesMastersList: 'RecipesMastersList',
  EditRecipesMasters: 'EditRecipesMasters',
  AddRecipesMasters: 'AddRecipesMasters',
  MiscellaneousList: 'MiscellaneousList',
  EditMiscellaneous: 'EditMiscellaneous',
  AddMiscellaneous: 'AddMiscellaneous',
  ItemMastersList: 'ItemMastersList',
  AddItemMasters: 'AddItemMasters',
  EditItemMasters: 'EditItemMasters',
  MyOrders: 'MyOrders',
  TermCondition:'TermCondition',
  PrivacyPolicy:'PrivacyPolicy',


  //chefSignUp

  ChefSignUp: 'ChefSignUp',

  //chefSell
  ChefNameList: 'ChefNameList',
  ChefEditName: 'ChefEditName',
  ChefSelfBottomBar: 'ChefSelfBottomBar',
  chef_tab_bar: {
    ChefHome: 'ChefHome',
    ChefMenuList: 'ChefMenuList',
    ChefNotification: 'ChefNotification',
    ChefProfile: 'ChefProfile',
  },
  ChefNotification: 'ChefNotification',
  ChefMyOrders:'ChefMyOrders',

  // student

  StudentSignUp: 'StudentSignUp',
  StudentSelect: 'StudentSelect',
  StudentBottomBar: 'StudentBottomBar',
  StudentMenuList: 'StudentMenuList',
  StudentCheckOut: 'StudentCheckOut',
  student_tab_bar: {
    StudentHome: 'StudentHome',
    StudentProfile: 'StudentProfile',
    StudentNotification: 'StudentNotification',
    StudentOrderHistory: 'StudentOrderHistory',
  },
  FoodCart: 'FoodCart',
};
